enBloc-org/kindly

components/messaging/ConversationsList.tsx, components/messaging/CoversationStateHandler.tsx, components/messaging/OpenConversation.tsx
closes #16 
ConversationsList now shows a shortened version of the latest message in that conversation. If no messages have been exchanged it will display "no messages yet..."
In the process I corrected the OpenConversationProps as it was unnecessarily creating a redundancy in our dot notation and causing some false type errors. As a result, OpenConversation now only receives two props - yey for less drilling 🕳️ 🎉
=> Shortened message

.gitignore, README.md, components/icons/tickIcon.tsx, package-lock.json, package.json, playwright-ct.config.ts, playwright/index.html, playwright/index.tsx, tests/ConversationCard.spec.tsx, tests/MessageCard.spec.tsx, tests/addbutton.spec.ts, tests/login.spec.ts, tests/profileButton.spec.ts
Added unit tests for components in messaging feature❗️
This PR includes tests for:
- ConversationCard.tsx
- MessageCard.tsx
playwright `ct-react` is an experimental package from playwright that includes a new fixture allowing us to render a component for our tests. It's working really well and allowed me to create basic tests for the functionality in our components but it did conflict with the imports of the original library.
**Issue:** Essentially, it does not like it if you import `'@playwright/experimental-ct-react'` in one file and `'@playwright/test'` in another. 
**Fix:** However, the experimental package includes all the original fixtures and I migrated all previous tests so that they still run 👍
`npm run test-ct`
I could not get our tests to compile properly with the `@` syntax …
=> Testing components

app/globals.css, components/messaging/MessageCard.tsx
closes #45 
Edited UI on MessageCard component to match the style guide from the Product Owner.
Edited the previous `.message-card__self` and `.message-card__other` classes for better readability.
`globals.css` now has`.message-card` and `.green-border-card`.
The class `.green-border-card` can be reused across components in the messaging feature.
- **Date stamp on messages**
The style guidance requires a specific format for dates which is not matched in this PR. The guide asks for `16 February 2024` and the version on this pr shows `2024 02 16`
Updating this could be done in the component via a helper function for this specific purpose but it would be better done in the model where we recover that information probably and I think there is currently work being done with that database call …
=> style MessageCard component

components/DeleteConvoButton.tsx, components/DeleteConvoModal.tsx, components/messaging/ConversationsList.tsx, utils/messaging/deleteConversation.ts
Added a model for deleting a conversation. It is not visible in the code but I updated cascade settings on supabase for the userconvo and messages table. The update makes it so if a conversation row is deleted all rows linked to it by foreign key are also deleted this means the related messages and user conversations should vanish (its worked without side effects in tests so far) After that I added a modal containing a button that deletes runs this function. 
its worth noting that when this button is clicked nothing visibly happens until page reload. I am surprised because in my head supabase live watching should be re-rendering the conversation list. Maybe someone with more knowledge can let me know why that is not happening
=> Delete conversation resolves #8

app/(dashboard)/conversations/page.tsx, app/(dashboard)/conversations/useConversation.tsx, components/messaging/ConversationProvider.tsx, components/messaging/ConversationWrapper.tsx, components/messaging/ConversationsList.tsx, components/messaging/CurrentConversation.tsx
- We created a ConversationWrapper component that contains the ConversationsList and CurrentConversation
Rendering these directly on the page component is not possible because we need to access state within these component. We could not access the state provided by conversationProvider on the page component because it is not compatible server side.
- We have added showConversationList, setShowConversationList to conversation provider
- useConversation (where we define the default context) has been updated accordingly
- The biggest (potentially most controversial change) we made was removing the useEffect from CurrentConversation.tsx. This was updating the currentConversation value but as this is already being done by updateOpenConvo in ConversationsList.tsx it prevented the info fetched …
=> Issue58 toggle view

README.md, components/messaging/ConversationCard.tsx, tests/ConversationCard.spec.tsx, tests/messaging.spec.ts
- ConversationCard component test has been refactored according to changes to the component (we're passing different props to it)
- ConversationCard has some text hard coded on to it so the test will need updating when this is updated to come from the db
- isClickable component test was previously using the conversation_id which we're no longer passing to the component so I have simplified it with a number increase
=> #87/conversation card test

components/messaging/CurrentConversation.tsx, components/messaging/MessageCard.tsx, utils/messaging/formatTimeStamp.ts
Added markers for each new day that are only visible if the user is scrolling through messages - pretty much emulated the behaviour of any major messaging app out there.
This div is only rendered whenever the date of the message is a different day from the previous message - this is done with an evaluation in the .map method using the index value which we are now calling there.
Date Markers have the following behaviour:
- Will stay at the top when scrolling and replace one-another in sequence
- Will fade out after 3 seconds of the user no longer scrolling
- Will stay centred in any screen size
- Will always be juxtaposed over MessageCards
The following lines will have to be reviewed if we are changing the return value of the date on our database query, which I am happy to take on in a …
=> #77/date markers

app/globals.css, app/styles/messaging-styles.css, components/messaging/ConversationWrapper.tsx, components/messaging/CurrentConversation.tsx, components/messaging/MessageCard.tsx, tailwind.config.js
-Styled message components to look like figma mockup
-Updated the tailwind config  to contain the colours for messaging (bg-secondary-(gray and green)).
-Styled the CurrentConversation component so it has correct height and takes into account the header and mobile nav bar.
-merge this branch with dev.
Mobile view:
Desktop:
=> #76/message card styling

components/messaging/CurrentConversation.tsx
Supabase channel is now only actively listening to changes on the currentConversation
Closes #90
Before enacting any changes to the UI our supabase websocket is now checking whether the currentConversation ID matches the ID of the conversation that sent a payload with the `INSERT` action on the `realtime messages` channel.
This removed the bug reported in this issue.
`CurrentConversation.tsx` has had an evaluation added to the `useEffect()` handling re-render for new messages.
No changes to UI 🙅 
No documentation needed as this was just a bug fix - the app behaves the same way we intended before.
No new tests as there was no feature added.
The bug reported was noticed when two developers were working on the `/conversations` route in the same server so I don't really see a test that I …
=> #90/bugfix-supabase-channel

package-lock.json, package.json
relates #155
**Closes #155**  
When users run npm install `Next` is not installed automatically as a dev dependency
- `package.json` && `package-lock.json` edited with Next moved to dev-dependecies
No UI changes 🚫 
This issue did not require changes to documentation
No changes to the behaviour that required new tests. Prior tests passing
=> build: installed next as dev dependency instead of dependency

components/AuthForm.tsx
Relates #159 
On the Auth page there were not ID for email and name. It was working as expected but this may induce errors on the browser's autocomplete. 
/components/Auth.Form.tsx
=> #159/incorrect use of label for

.github/BEFORE_YOUR_FIRST_ISSUE.md
**Relates #208 
This is to add commands for Windows users when setting up a local database [BEFORE_YOUR_FIRST_ISSUE.md](https://github.com/enBloc-org/kindly/blob/dev/.github/BEFORE_YOUR_FIRST_ISSUE.md).
The following commands were added:
```
npm install supabase --save-dev
npx supabase login
npx supabase start
```
The commands were successfully tested on my and @YuraPetrovskyi's machines 👌
I've only updated the BEFORE_YOUR_FIRST_ISSUE.md file. However, after installing the Supabase CLI on my machine, my package.json was updated as below:
🙋The question I have: should I also commit changes for package.json and package-lock.json files? I haven't done it in this PR. Thanks 😊
=> #208/review documentation for windows

README.md
docs: updated README.md with the relevant link to PRIVACY.md
relates #209
**Relates #[209] <u>OR</u> Closes #[issue number]**  
There's a link in the README.md file that is intended to give visitors to the repo a quick view of the privacy statement.
This should navigate directly to the already created PRIVACY.md document in our repo.
updated README.md with the relevant link to PRIVACY.md
no changes
The PRIVACY.md file should be displayed along with the readme, license and code of conduct in the repo
I tested the link and it redirects to PRIVACY.md
=> #209/Link 🔗 to PRIVACY.md from README.md

.github/workflows/stale.yml
**Closes #232**  
Trivial cleanups on the stale issue/PR workflow.
`.github/workflows/stale.yml`:
- 325a157 Removed an invalid action input.
- Is causing the `Unexpected input(s) 'GITHUB_TOKEN'` warning in the workflow runs ([example](https://github.com/enBloc-org/kindly/actions/runs/9295893813)).
- 7378aa2 Removed an unnecessary environment variable.
- `actions/stale` already sets `repo-token` with the token by default ([doc](https://github.com/actions/stale?tab=readme-ov-file#repo-token)).
Here's [an example of a workflow run](https://github.com/mnixo/kindly/actions/runs/9302334127) with the proposed changes.
=> #232/stale workflow input

.github/BEFORE_YOUR_FIRST_ISSUE.md
**Closes #243**  
Adds a reference to the Node.js version that should be used.
If there is no set Node.js version as of yet, my suggestion is to use [Node.js 20](https://nodejs.org/en/about/previous-releases):
- Is the Active LTS until ~October 2024.
- Scheduled maintenance window until ~April 2026.
`.github/BEFORE_YOUR_FIRST_ISSUE.md`
N/A.
This is a documentation PR.
Tested locally using `node@v20.14.0` and `npm@10.7.0`.
=> #243/add Node.js version

.github/BEFORE_YOUR_FIRST_ISSUE.md, package-lock.json, package.json
**Closes #216**  
* Supabase is installed as a dependency and can be used with `npx` on all platforms.
* Does not require any other installs (with `brew` or similar).
* Updates the dependency to a newer version (`1.176.10`).
* `.github/BEFORE_YOUR_FIRST_ISSUE.md` with all the doc updates.
* `package.json` with the version update.
* The `supabase` scripts require no changes. `npm` uses locally installed binaries when running scripts ([reference](https://stackoverflow.com/a/77716087)).
* `package-lock.json` is automatically updated after a clean `npm i` (using `npm` `10.7.0`).
Unifies and simplifies the existing documentation as there is no longer need for:
* Installation of the `supabase` CLI.
* UNIX/Windows specific commands.
Manual tests were performed for different scenarios that are …
=> #216/supabase cli usage

.github/workflows/storybook.yml, package-lock.json, package.json
**Relates #273**  
- Quick fix on a dependency vulnerability: GHSA-3h5v-q93c-6h6q.
- Add a new GitHub Actions workflow to run the Storybook interaction tests, based on the existing play functions.
- Runs on PRs targeting the `dev` branch.
- Runs on pushes to the `dev` branch.
There are also Cypress E2E tests in the project. We can also run them in CI, if need be.
- `package.json` and `package-lock.json`, for new dependencies.
- `storybook.yml`, the new workflow file.
https://github.com/mnixo/kindly/pull/11 used to verify that the workflow runs as intended [before](https://github.com/mnixo/kindly/actions/runs/9751025324/job/26911727678) and [after](https://github.com/mnixo/kindly/actions/runs/9751077718/job/26911885211) merge.
=> Add Storybook interaction tests to CI

components/buttons/NewConversationButton.tsx
HOT FIX
resolves issue with items being reserved automatically when a new conversation is started
`NewConversationButton.tsx`
none
none
none - tests are all passing
=> fix: stopped items from being reserved on start new conversation

.github/workflows/cypress.yml, .github/workflows/storybook.yml, cypress/e2e/anonymous.cy.js, cypress/e2e/item.cy.js
**Closes #286**  
Introduces a new GitHub Actions workflow to run the Cypress E2E tests.
* `.github/workflows/cypress.yml`: The new workflow file.
* Runs on `dev` and `main`.
* Times out after 10 minutes, preventing hanging workflow runs.
* Installs the project dependencies.
* Starts Supabase.
* Sets the environment variables.
* Simultaneously starts the app and runs the E2E tests using the Cypress action.
* `.github/workflows/storybook.yml`: Runs the storybook tests also on `main`.
* `cypress/e2e/anonymous.cy.js`: Adds redirect timeouts to make tests more resilient (in CI, tests run slower). The timeout represents the maximum time the test is allowed to wait before it fails.
* `cypress/e2e/item.cy.js`: Fixes an import.
Have a look at the checks on this PR 😉
=> Add Cypress tests to CI

app/(auth)/signup/page.tsx, cypress/e2e/authorisation.cy.js, cypress/fixtures/URLs.json, cypress/support/page_objects/signupPage.js
**Closes #301**  
Trying to signup an existing user now redirects to /login with an explicit message.
Explicit url is being passed to the `emailRedirectTo` option on .signUp()
`signup/page.tsx` - adding email redirect option
`cypress/**` - extended E2E tests to specifically test attempting to signup an existing user
n/a
n/a
New tests described above.
=> #301/redirect on signup

.github/TESTING.md, package.json
**Closes #319**
Cleans up the `package.json` scripts and adds documentation on how to run the Cypress E2E tests.
- `package.json`:
- Removes Playwright `test` and other related scripts.
- Proposes to remove the `changed` and `test:changed` scripts entirely. Running all the tests is not that expensive and safer.
- Adds `start-test` command.
- Starts the app in dev mode and runs the E2E tests.
- Still requires Supabase to be started first.
- The mixed logs of the app and the tests is not very easy to follow. It might be more practical to use different terminals for debugging.
- `.github/TESTING.md`: adds documentation on how to run and debug the Cypress E2E tests.
=> Update testing scripts and documentation guidance on E2E with Cypress

supabase/seed.sql
relates #296
This Pull Request addresses the issue related to the sequence value for "messages_id_seq" in the dev environment. The sequence was updated to 14 to correct discrepancies in IDs.
**Closes #296**  
It only changes one line in `seed.sql` file: 
`SELECT pg_catalog.setval('"public"."messages_id_seq"', 14, true);`
No UI changes were made in this PR.
No changes to documentation are needed for this PR.
No tests are needed at the moment for this PR.
=> #296/fix new messages fail

.github/workflows/auto-unassign-issue.yml
**Closes #324**  
`.github/workflows/auto-unassign-issue.yml`:
* Fixes the runner identifier, which was causing runs to hang indefinitely.
* Fixes the version of action used, preventing uncontrolled version bumps.
[Example of a successful run of the workflow in my fork](https://github.com/mnixo/kindly/actions/runs/10288666824).
=> Fix Auto Unassign Inactive Issues workflow

.github/workflows/staging.yml
**Closes #326**  
* `.github/workflows/staging.yml`: The full "Deploy Migrations to Staging" workflow only runs when the necessary `SUPABASE_PROJECT_ID` secret is configured.
Contributors are no longer met with a unsolvable failed status on the `dev` branch of their fork.
This still leaves the door open for any contributor to set their own secret values on their fork. If they do, the workflow will automatically update their own instance, just like it does in the original repository.
The functionality should remain the same on the `dev` branch of the original repository.
[See this example of a run in the context of a fork](https://github.com/mnixo/kindly/actions/runs/10326029338/job/28588774064).
=> Skip staging deployment when secrets are not set

app/(dashboard)/about/page.tsx, app/(dashboard)/layout.tsx, app/(dashboard)/search/page.tsx, app/globals.css, components/Footer.tsx, components/Header.tsx, components/ItemCard.stories.ts, components/ItemCard.tsx, components/ItemDetails.tsx, components/search/ItemDisplayContainer.tsx
**Closes #292 **  
This PR expands a bit on the issue and seeks to resolve a few layout issue with the app, specifically with the mobile experience. It seeks primarily to deal with stying issue on the search and about routes.
Story files updated to reflect new information being displayed as well as show postage covered state.
=> #292  Improved mobile styling and item card layouts

.gitignore, README.md
**Relates #333  
The link in the README file under "For details on the different roles you can take on" should redirect users to the correct GOVERNANCE.md
Readme file
The link in the README file under 'For details on the different roles you can take on' 
has been updated to redirect to the correct GOVERNANCE.md file, located at
https://github.com/enBloc-org/kindly/blob/dev/.github/GOVERNANCE.md.
I tested it manually, and it works.
=> Fix broken "Roles and Responsibilities" link in the README

.github/workflows/stale.yml
relates #328
**Closes #328**  
I've added an exemption for the issues with the label 'in review'. To make it work, we would need to create a label 'in review' as following: 
1. Someone who has access to add new labels (probably @camelPhonso ) should go to [labels ](https://github.com/enBloc-org/kindly/labels) and click 'New label'
> ![image](https://github.com/user-attachments/assets/0db52d4e-ea93-410a-83c8-dafdf9651a65)
2. Add 'in review' label. (The label name should be exactly the same as in the stale.yml file)
> ![image](https://github.com/user-attachments/assets/4c0ffc8b-2acd-42bf-9444-61baddbd3343)
3. The label should be added ❗ manually to the issues that are in review. This can be done by anyone (at least I have access to add a label) …
=> #328/feat: exclude issues in review from stale

app/(dashboard)/edit-item/[id]/page.tsx, app/styles/messaging-styles.css, components/menus/EllipsisMenu.tsx, components/messaging/ConversationCard.tsx, components/messaging/ConversationsList.tsx, components/messaging/MessageForm.tsx, cypress/e2e/messaging.cy.js, cypress/fixtures/URLs.json, cypress/support/page_objects/conversationsPage.js, supabase/migrations/20240906121523_fix_return_type_for_select_user_conversations.sql
**Closes #329**  
Bug fix for displaying a notification dot over any conversation card to a conversation with unread messages.
Extended tests to our messaging feature to avoid regression.
- `supabase/migrations/20240906121523_**.sql` - new migration file recreating the `fetch_user_conversations` function in our database to return the value of `has_unread_messages` in each conversation
- `ConversationsList.tsx` - added useEffect to update `notificationsList` local state when changes occur to `allConversations` in the wider context.
- `components/messaging/**.tsx` && `app/styles/messaging-styltes.css` - lifted some stylings and added `name` attributes to some elements for testability of the messaging functionality
- `messaging.cy.js`, `URLS.json` && `conversationsPage.js`- new testing suite …
=> #329/fix unread

.github/CONTRIBUTING.md, types/messagingTypes.ts
**Closes #360**  
This PR is only for the changes to documentation that explain the current rollback plan. A snapshot branch has already been setup with the currently stable version of the platform and can be found by following the documentation as per the changes committed here.
- `CONTRIBUTING.md`
n/a
Sets out guidance on what to do if a contributor spots a breaking issue in production and explains in which cases to use the rollback, who can perform one and how to do it if it is necessary.
No changes to the codes behaviour. All previous tests are passing.
=> docs: documented rollback strategy
