enBloc-org/kindly

utils/supabase/types.ts

added types to match new table

Types are added (worth a spell check)

---

components/messaging/ConversationsList.tsx
components/messaging/MessageForm.tsx

Fixed prevent default call in message for submit handler.
Closes #29

Fixed preventDefault call

---

app/(dashboard)/conversations/page.tsx
app/(dashboard)/conversations/useConversation.tsx
components/messaging/ConversationProvider.tsx
components/messaging/ConversationsList.tsx
components/messaging/CurrentConversation.tsx

sorry for the branch name typo but this just replaces open conversation with current conversation which was all that was left to resolve issue 33

Current convo Refactor/issue#33

---

app/(dashboard)/item/[id]/page.tsx
app/api/send-email/route.js
components/buttons/NewConversationButton.tsx

Brought back emails so you get an email when a new conversation is started. Cleared old email button off of item page now that I have taken the code I needed from it

email now sent when conversation starts

---

README.md
package.json
playwright-ct.config.ts
tests/addItemRoute.spec.ts
tests/auth.setup.ts
tests/profileRoute.spec.ts

**Closes #110 **
Added a new script that allows developers to run tests only on files that have been edited in their current branch - `npm run test:changed`
The old script `npm run ci` has been edited to be `npm run test:all` for clarity
Also refactored the setup so that all test scripts start a server on :3645 instead of :3000 in order to avoid clashing with our development servers.
- `package.json` has a new script and slight changes to old test scripts
- `playwright.config.ts` has been edited to set the base url for all tests for a different port from our dev
No changes to the UI 🛑 
`README.md` has been edited with guidance on the new test scripts.
No new tests as this PR is for testing setup. All existing tests are passing.

#110/new test script

---

.github/CONTRIBUTING.md

**Closes #101**
Added documentation providing guidance for new developers looking to contribute to Kindly.
I mention some links within the CONTRIBUTING.md doc that are not actually set in this PR:
- Link to Discord needs to be added, if that is infact where we want to send people for questions
- Link to BEST_PRACTICES.md needs to be added (the file has not been created yet and is in another issue)
- Link to installation guide needs to be added
**We originally defined an issue to create a file called BEFORE_YOUR_FIRST_PR.md, but I think now we should maybe make that an installation guide instead** ❓❓ 
`CONTRIBUTING.md` added
No changes to UI ⛔ 
This PR is for Documentation - only one Markdow file was added.
No Changes to behaviour so no new tests. All prior tests are passing

#101/contributing doc

---

README.md

This is a temporary version of the updated readme! More changes to come
relates #105

fix: temporary readme changes

---

.github/BEFORE_YOUR_FIRST_ISSUE.md
README.md

**Closes #130**
Wrote a Before First Issue Doc. Moved installation guide and technologies used from read me into this doc.
README.MD
Wrote a Before First Issue Doc. Moved installation guide and technologies used from read me into this doc.

Created Before First Issue Doc

---

.github/PULL_REQUEST_TEMPLATE.md

**Closes #143**
Edited the `PULL_REQUEST_TEMPLATE.md` so you all fill it in properly 🧂 
- `PULL_REQUEST_TEMPLATE.md` now asks devs to fill in the 'relates' "OR" 'closes' tag for the issue the PR is responding to
No UI changes 🛑 
This is a documentation Issue. All changes outlined above.
This issue does not touch any code - no new tests needed.

#143/edit-pr-template

---

.github/BEFORE_YOUR_FIRST_ISSUE.md

small change to make sure users are on the dev branch if they dont know to be

 Before your first issue.md #104

---

components/messaging/MessageForm.tsx

**Relates #120**  
This PR prevents the user from sending empty messages. 
- Sprint: Added an Error handler and included a State for it. 
This involved:
- Created a `trimmedMessage` variable inside `handleSubmit` to account for empty strings and whitespace.
- Included an Error state handler.
- Rendered the Error message.
`components/messaging/MessageForm.tsx`
The error message appears when the user attempts to send an empty message, immediately disappear when the user clicks the input box again.
None needed.
I believe these are minor changes that do not require further tests, however please let me know if I need to add any.

#120/prevent sending empty messages

---

.github/CONTRIBUTING.md
README.md

**Closes #174**  
New contributors were not spotting the invite to the discord server so that has been updated in our documentation now.
- `CONTRIBUTING.md` has only had the discord invite link updated as I created a new one
- `README.md` now mentions connecting with the core team via discord right under our guidance to check the rest of the documentation
No changes to the UI 🙅 
This is a documentation issue so all changes are listed above
No changes to the behaviour of the code in this pr

#174/update discord invite

---

package-lock.json
package.json

closes #157
** Closes #157 **  
Include here a short description of what behaviour this Pull Request introduces.
Outline any new dependencies introduced.
Updated next/font dependency
Package.json
Package-lock.json

updates package to replace deprecated font

---

.github/LICENSE.md
README.md

**Closes #179**  
Include here a short description of what behaviour this Pull Request introduces.
Outline any new dependencies introduced.
Detail in documentation changes
No changes to UI 🙅 
- `LICENSE.md` created 
- `README.md` updated with an explicit reference to the license applied as per guidance by the Free Software Foundation
I'm suggesting here that we apply the GNU General Public Use license for Kindly as it (in a shortened explanation) allows other developers to use, study and adapt the code while setting the expectation to apply the same license to any new versions developed and pass on the source code (and a copy of the license) if a new product is developed from our source code.
The other very common license for open source projects is the MIT license but the GNU stops …

#179/gnu license

---

README.md

relates #188
**Relates #188  
This is to update the wording to "Ukrainian refugees in the United Kingdom" in the README.md file
Only the README.md file is changed 
No changes to UI 
The issue itself was to update the working in the Readme file :smiley: 
No tests needed

docs: updated  wording in the README.md

---

app/(dashboard)/add-item/page.tsx
app/(dashboard)/profile/page.tsx
components/form/ProfileEdit.tsx
components/form/UploadImageInput.tsx
types/supabaseTypes.ts

**Relates #177 
User can change their Username without uploading a image. 
ProfileEdit.tsx
UploadImageInput.tsx
supabaseTypes.ts
None
None
None

#177/username editing without image upload

---

app/(dashboard)/add-item/success/page.tsx

**Relates #[issue number] <u>OR</u> Closes #[issue number]**  
Include here a short description of what behaviour this Pull Request introduces.
Outline any new dependencies introduced.
Include one to two lines on the necessary changes to each file.
If this PR includes changes to the UI include a **screengrab** of the alterations in review.
Include an outline of why Documentation needed to be updated with this PR
Include a description of any tests added - if none have been added explain why.

typo fixed

---

components/Header.tsx
components/navigation/KindlyLogoLink.tsx

Closes #222
This hotfix creates a component for the kindly logo to follow DRY principles and updates the logic to correctly show the back or logo in the correct views.
components/Header.tsx - uses logo component and updates rendering logic
components/navigation/KindlyLogoLink.tsx - creates component for reusability
Include one to two lines on the necessary changes to each file.

Hotfix - backarrow does not show in desktop view

---

.github/BEFORE_YOUR_FIRST_ISSUE.md
.github/workflows/move-issue-to-backlog.yml
.github/workflows/move-issue-to-in-progress.yml

**Closes #230**  
Hot Fix for the broken display of our welcome video for new contributors
- `BEFORE_YOUR_FIRST_ISSUE.md` - corrected the display of our welcome video with a thumbnail linking to the loom page
- `move-issue-to-backlog.yml` & `move-issue-to-in-progress.yml` - corrected project title in workflows. The scripts were technically working but the project title was wrong and stopped the automation from working
No changes to the codebase
All changes described above
No changes to the codes' behaviour

docs: fixed the display of our welcome video for new contributors

---

.github/BEFORE_YOUR_FIRST_ISSUE.md
components/messaging/ConversationWrapper.tsx
package.json
supabase/migrations/20240604162858_sort-by-created-at.sql
utils/sortByDate.ts

Does what it says in the description.
**Closes #71**  
components/messaging/ConversationWrapper.tsx - Updates select message name and calls sort util when assigning the data to state.
- utils/sortByDate.ts - util function to sort conversation objects by date.
- package.json - Adds script to run supabase migration.
- supabase/migrations/20240604162858_sort-by-created-at.sql - migration doc for postgres function update to sort by message created at. 
- .github/BEFORE_YOUR_FIRST_ISSUE.md - adds instruction about migration script

Initial render of ConversationWrapper sorts conversations by message timestamp

---

.github/FUNDING.yml

**Closes #264**  
This PR creates a sponsorship link in our repo directing readers to a Go Fund Me campaign for Trafalgar Girls.
- `FUNDING.yml` is a common `.yml` script that will set a link in our repo pointing visitors to the ongoing Go Fund Me campaign for Trafalgar Girls.
No Changes 🙅
This is a documentation PR. All changes described above
This PR does not affect the behaviour of the code. No tests required.

Add Sponsorship link

---

app/(dashboard)/add-item/page.tsx
app/(dashboard)/add-item/success/[itemId]/page.tsx
components/buttons/ButtonRounded.tsx
supabase/models/insertRow.ts

Closes #192  
feat: Implement URL parameters for success page and new item navigation
- Created a dynamic route for the success page under `app/(dashboard)/add-item/success/[itemId]/page.tsx`
- Updated the `SuccessPage` component to retrieve `itemId` of added item from URL parameters
- Modified `AddItemPage` to redirect to the success page using dynamic route with `itemId`
- Updated `insertRow` function to include returning data after insertion
- Improved URL clarity and SEO by using clean, hierarchical paths for navigation
style: Add container for buttons and set equal width
- Added a container around buttons on the SuccessPage for better layout structure
- Updated ButtonRounded component to accept a 'width' prop, allowing buttons to have equal width
- Applied the 'width' prop to buttons …

#192/add item link on success

---

README.md

Closes #271  
Some of the information the issue requested we introduce was already in the readme, but I have changed the layout to make it a little clearer.
What do you think of this:
"Kindly is currently in beta stage, meaning that it is being tested by a small community of volunteer testers. If you want to be a part of the testing community, contact XYZ"
Is the testing community open to anyone who wants to get involved? If so, should I put the trafalgar girls contact details in here?
readme (see above)
n/a

add section for users to readme

---

components/Header.stories.tsx

relates #244
**Relates #244 
Added a new story for the Header component. Currently, it only reflects how the Header component should look for different screens (mobile or desktop) with the possibility of manually changing the parameters.
Created a new file - Header.stories.tsx
It involves only a visual reproduction of the component with the possibility of manually changing the parameters, so no tests are provided at this step.

added story for Header component

---

app/(auth)/delete-account/page.tsx
app/(auth)/login/page.tsx
app/(dashboard)/add-item/page.tsx
app/(dashboard)/conversations/page.tsx
app/(dashboard)/edit-item/[id]/page.tsx
app/(dashboard)/item/[id]/page.tsx
app/(dashboard)/profile/page.tsx
components/AuthForm.tsx
components/form/AddNewItemForm.tsx
middleware.ts

**Closes #312**  
This PR is a refactor that moves all checks for a session from our private areas into the middleware that was previously unused in the structure of the code. No new features have been added, though there are slight adjustments in how we communicate status to the user.
The codebase previously included some instances of `getSession()` and others of `getUser()` when checking for a session. Here I have removed all other checks and left only a call for `getUser` in the middleware. According to official documentation this is the safer option as it verifies the users JWT on the server and although `getSession` would be a faster call we have mitigated any concern for performance by confining it to a single call in the middleware.
- `middleware.ts` - now checks for an existing …

#312/middleware

---

app/(dashboard)/item/[id]/page.tsx

- [x ] My changes generate no new warnings or errors
- [] New and previously existing unit tests pass locally with my changes
**Closes #348 **  
fixes error where refugee accounts could not view items
item[id]/page
none
none
none

relates #348 fixes hopefully

---

app/page.tsx

Relates: #346
** Closes #346**  
This PR fixes the front-end issue where the main content on the homepage wasn't fully visible on small devices. Thre was lack of spacing between the main content and the footer on smaller screens. The solution was to add a bottom margin (mb-24) to the main content area:
> app\page.tsx:
> `<main className='mb-24 flex flex-grow flex-col'>`
> 
N/A
Tested manually on small screens. No additional automated tests are needed for this

#346: Fix main content visibility on small devices

---

components/form/AddNewItemForm.tsx
components/form/ProfileEdit.tsx
components/form/UploadImageInput.tsx
cypress/e2e/item.cy.js
cypress/support/page_objects/basePage.js
package-lock.json

**Relates #190  
All form fields in AddNewItemForm component have the message "This field is required" by default.
This uses the error-message style
AddNewItemForm .tsx
This PR changes the UI only
NA
No tests have been added in this PR.

#93/form required field lable

---

components/form/AddNewItemForm.tsx
components/form/SizeSelector.tsx

**Relates #[[#366](https://github.com/enBloc-org/kindly/issues/366)] **  
- AddNewItemForm.tsx (deletes onSubmit; refactors the form using react-hook-form library; extracts inputs into separate components; handles error with errors object form formState) and a separate custom component (ErrrMessage.tsx)

Missing prop bug fix

---

types/messagingTypes.ts

Relates #376
**Closes #376 **  
This PR fixes a type error to mirror a change made to the v1-merge to main branch that was preventing that branch from being deployed and merged properly. 
- ```types/messagingTypes.ts``` - adds   partner_has_deleted property to type to correctly reflect the data that is being fetch from the web-socket when a new conversation is being added when a user is on the conversation page. 
n/a
n/a
n/a

fix: updates type to prevent type error
